/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-109065-gb653352bd8-20221112"
#endif /* AVUTIL_FFVERSION_H */
